services:
  - type: worker
    name: ton_sales_bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: TON_WALLET
        sync: false
      - key: TON_WALLET_HEX
        sync: false
      - key: TON_API_KEY
        sync: false
      - key: CHECK_INTERVAL
        value: "30"
